development:
  adapter: postgresql
  encoding: unicode
  database: fscalendar_development
  pool: 5
  username: glowfori
  password: glowforipass
  port: 5432
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: fscalendar_test
  pool: 5
  username: glowfori
  password: glowforipass
  port: 5432
  host: localhost
  min_messages: WARNING
